# Generated by Django 5.2.8 on 2025-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('body', models.TextField()),
                ('phase', models.CharField(choices=[('1927', '1927'), ('1985', '1985'), ('2000', '2000'), ('2015', '2015')], default='1927', max_length=20)),
            ],
            options={
                'ordering': ('phase',),
            },
        ),
        migrations.CreateModel(
            name='contacus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Audio', 'Audio'), ('Books', 'Books'), ('Gallery', 'Gallery'), ('General', 'General')], default='General', max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='loginFormdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginemail', models.CharField(max_length=100)),
                ('loginpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wishdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('astrology_message', models.CharField(max_length=300)),
                ('mobilenumber', models.BigIntegerField(default=0)),
            ],
        ),
    ]
