# Generated by Django 5.2.7 on 2025-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('image', models.FileField(default='', upload_to='bookimages')),
                ('pdf', models.FileField(default='', upload_to='bookpdfs')),
            ],
        ),
    ]
