# Generated by Django 5.2.8 on 2025-12-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Location',
            new_name='location',
        ),
    ]
