# Generated by Django 5.2.7 on 2025-10-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('astrology_message', models.CharField(max_length=300)),
            ],
        ),
    ]
