# Generated by Django 5.2.8 on 2025-12-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_location_author_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='authorname',
        ),
    ]
