# Generated by Django 5.2.7 on 2025-10-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_wishdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishdata',
            name='mobilenumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
