# Generated by Django 5.2.7 on 2025-10-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_wishdata_mobilenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
