# Generated by Django 5.2.7 on 2025-10-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdata',
            new_name='signupFormdata',
        ),
    ]
