# Generated by Django 5.2.7 on 2025-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_userdata_signupformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginFormdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginemail', models.CharField(max_length=100)),
                ('loginpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resetpasswordFormdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resetemail', models.CharField(max_length=100)),
                ('restnewpassword', models.CharField(max_length=100)),
                ('restconfirmnewpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='signupformdata',
            old_name='email',
            new_name='signupconfirmpassword',
        ),
        migrations.RenameField(
            model_name='signupformdata',
            old_name='name',
            new_name='signupemail',
        ),
        migrations.RenameField(
            model_name='signupformdata',
            old_name='password',
            new_name='signupname',
        ),
        migrations.RenameField(
            model_name='signupformdata',
            old_name='retypepassword',
            new_name='signuppassword',
        ),
    ]
