# Generated by Django 5.2.7 on 2025-10-23 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_loginformdata_resetpasswordformdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginformdata',
            name='logintime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loginformdata',
            name='logintimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loginformdata',
            name='logintimezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
