# Generated by Django 5.2.7 on 2025-10-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_loginformdata_logintime_loginformdata_logintimestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginformdata',
            name='logintimestamp',
        ),
        migrations.AddField(
            model_name='loginformdata',
            name='loginip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
