# Generated by Django 5.2.7 on 2025-10-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_loginformdata_logintimestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginformdata',
            name='loginip',
        ),
        migrations.RemoveField(
            model_name='loginformdata',
            name='logintime',
        ),
        migrations.RemoveField(
            model_name='loginformdata',
            name='logintimezone',
        ),
    ]
