# Generated by Django 5.2.7 on 2025-10-30 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_loginformdata_loginip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacusdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='resetpasswordFormdata',
        ),
        migrations.DeleteModel(
            name='signupFormdata',
        ),
    ]
