# Generated by Django 5.2.7 on 2025-10-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_contacusdata_delete_resetpasswordformdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Audio', 'Audio'), ('Books', 'Books'), ('General', 'General')], default='General', max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contacusdata',
        ),
    ]
