# Generated by Django 5.2.7 on 2025-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_contacus_delete_contacusdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacus',
            name='subject',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Books', 'Books'), ('Gallery', 'Gallery'), ('General', 'General')], default='General', max_length=200),
        ),
    ]
