# Generated by Django 5.2.8 on 2025-11-11 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_contacus_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacus',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='contacus',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contacus',
            name='subject',
            field=models.CharField(choices=[('A udio', 'Audio'), ('Books', 'Books'), ('Gallery', 'Gallery'), ('General', 'General')], default='General', max_length=200),
        ),
    ]
