# Generated by Django 5.2.8 on 2025-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_created_at_contacus_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('slug', models.SlugField(max_length=264, unique_for_date='publish')),
                ('body', models.TextField()),
                ('phase', models.CharField(choices=[('2009–2011', '2009–2011'), ('March 2011', 'March 2011'), ('December 2015', 'December 2015'), ('July 2020', 'July 2020')], default='2009–2011', max_length=20)),
            ],
            options={
                'ordering': ('-phase',),
            },
        ),
        migrations.AlterModelOptions(
            name='contacus',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='contacus',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='contacus',
            name='subject',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Books', 'Books'), ('Gallery', 'Gallery'), ('General', 'General')], default='General', max_length=200),
        ),
    ]
