# Generated by Django 5.2.8 on 2025-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_aboutdetails_alter_contacus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdetails',
            options={'ordering': ('phase',)},
        ),
        migrations.AlterField(
            model_name='aboutdetails',
            name='phase',
            field=models.CharField(choices=[('1927', '1927'), ('1985', '1985'), ('2000', '2000'), ('2015', '2015')], default='1927', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutdetails',
            name='slug',
            field=models.SlugField(max_length=264, unique=True),
        ),
    ]
